Repository dlang-community/containers, pull requests merged in 2018-03, with the labels that each got.

#102 Fix issue 101: avoid import deprecation message in DMD 2.079
  src/containers/internal/storage_type.d
Labels: Bug Fix, auto-merge-squash

#97 Fix issue #96 - DynamicArray should not call destructors for objects
  src/containers/dynamicarray.d
Labels: Bug Fix, auto-merge

#100 Extend DynamicArray ~= to accept array of values
  src/containers/dynamicarray.d
Labels: auto-merge

#103 Add byKey, byValue/opSlice, and byKeyValue to HashMap
  dub.json
  src/containers/hashmap.d
  src/containers/internal/hash.d
  src/containers/openhashset.d
  src/containers/ttree.d
  src/containers/unrolledlist.d
  test/compile_test.d
Labels: auto-merge-squash, enhancement

#106 Add Meson build definition
  .travis.yml
  meson.build
  subprojects/stdx-allocator.wrap
Labels: auto-merge
